### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by Nugine** [Nugine/simd-benches#1]
GitHub Actions:
+ [x] binary cache: cargo-criterion
+ [ ] dependabot

Crates:
+ [x] Add [simdutf](https://github.com/Nugine/simdutf-rs)
+ [x] Add [simdutf8](https://github.com/rusticstuff/simdutf8)

Pages:
+ [ ] Add readme
+ [ ] Better style?

Benches:
+ [x] Add utf8-to-utf16
+ [ ] Add utf16-to-utf8
